CruGlobal/kotlin-mpp-godtools-tool-parser

build.gradle.kts

currently the Kotlin cocoapods plugin only supports `DEBUG` and `RELEASE` configurations: https://github.com/JetBrains/kotlin/blob/master/libraries/tools/kotlin-gradle-plugin-api/src/main/kotlin/org/jetbrains/kotlin/gradle/plugin/mpp/NativeBinaryTypes.kt#L21-L22
This works around the limitation by sanitizing any configuration to one of the 2 supported types

Force CONFIGURATION to be debug or release only

---

.github/workflows/build.yml
build.gradle.kts
src/commonMain/kotlin/org/cru/godtools/tool/Utils.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/EventIdTest.kt

Kotlin/Native currently requires any object shared between the main and background threads to be immutable. This adds a second test task to run all of our tests on a background thread to ensure we aren't writing logic that only works on the main thread.

Run iOS tests on both the main thread and a background thread

---

src/commonMain/kotlin/org/cru/godtools/tool/model/Base.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Constants.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Manifest.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/tract/CallToAction.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/tract/Card.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/tract/Header.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/tract/Hero.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/tract/Modal.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/tract/TractPage.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/ColorTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/ManifestTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/TestColors.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/tract/CallToActionTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/tract/CardTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/tract/HeaderTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/tract/HeroTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/tract/ModalTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/tract/TractPageTest.kt
src/commonTest/resources/org/cru/godtools/tool/model/tract/call_to_action.xml
src/commonTest/resources/org/cru/godtools/tool/model/tract/card.xml
src/commonTest/resources/org/cru/godtools/tool/model/tract/header.xml
src/commonTest/resources/org/cru/godtools/tool/model/tract/header_defaults.xml
src/commonTest/resources/org/cru/godtools/tool/model/tract/hero.xml
src/commonTest/resources/org/cru/godtools/tool/model/tract/hero_ignored_content.xml
src/commonTest/resources/org/cru/godtools/tool/model/tract/modal.xml
src/commonTest/resources/org/cru/godtools/tool/model/tract/page.xml
src/commonTest/resources/org/cru/godtools/tool/model/tract/page_cards.xml
src/commonTest/resources/org/cru/godtools/tool/model/tract/page_modals.xml

- import hero model
- import tract page parsing logic
- adjust Hero tests
- import the Header model
- add the CallToAction model
- add a couple common color constants
- import Modal model
- import the Card model
- support parsing tract pages referenced by a manifest

Add Tract xml models

---

src/commonMain/kotlin/org/cru/godtools/tool/model/Category.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Constants.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Manifest.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Styles.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/StylesOverride.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Text.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/lesson/LessonPage.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/tract/Card.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/tract/Header.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/tract/Hero.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/tract/Modal.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/tract/TractPage.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/CategoryTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/ManifestTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/StylesTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/TextTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/lesson/LessonPageTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/tract/CardTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/tract/HeaderTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/tract/HeroTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/tract/ModalTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/tract/TractPageTest.kt

This PR utilizes the textScale Styles property to define base relative text sizes for various components.

Implement base textSizes utilizing textScale

---

src/commonMain/kotlin/org/cru/godtools/tool/model/Category.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/StylesOverride.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Text.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/tract/Card.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/tract/Header.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/tract/Hero.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/tract/Modal.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/tract/TractPage.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/CategoryTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/tract/CardTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/tract/HeroTest.kt
src/commonTest/resources/org/cru/godtools/tool/model/categories.xml

This PR makes it possible for the following properties to properly reflect fallback colors:
```kotlin
card.label.textColor
hero.heading.textColor
category.label.textColor
```

Reflect default text colors in the model

---

src/commonMain/kotlin/org/cru/godtools/tool/model/Category.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Constants.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/tract/Card.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/tract/Header.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/tract/Hero.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/tract/Modal.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/CategoryTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/tract/CardTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/tract/HeaderTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/tract/HeroTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/tract/ModalTest.kt

- Revert "use textScale to automatically size the Category label"
- Revert "scale the card label"
- Revert "use a custom textScale for the hero heading"
- Revert "use textScale to represent the relative size of Header text children"
- Revert "set a textScale for the Modal title text"
- Revert "apply a text scale to modals"

Revert hard-coded text-scales

---

build.gradle.kts

- upgrade to Kotlin 1.5.20
- the iOS workaround is still necessary

Upgrade to Kotlin 1.5.20

---

src/androidTest/java/org/cru/godtools/tool/internal/-AndroidTestingPlatform.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Manifest.kt
src/commonMain/kotlin/org/cru/godtools/tool/service/ManifestParser.kt
src/commonMain/kotlin/org/cru/godtools/tool/util/SetOnceProperty.kt
src/commonTest/kotlin/org/cru/godtools/tool/internal/-CommonTestingPlatform.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/CategoryTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/ManifestTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/service/ManifestParserTest.kt
src/iosTest/kotlin/org/cru/godtools/tool/internal/-IosTestingPlatform.kt
src/jsTest/kotlin/org/cru/godtools/tool/internal/-JsTestingPlatform.kt

- add a coroutines testing method
- make parseManifest suspendable
- make parse suspendable
- create a setOnce property that can be set only once
- update manifest parsing to parse pages and tips in parallel

Make the ManifestParser suspendable

---

src/commonMain/kotlin/org/cru/godtools/tool/ParserConfig.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Content.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/EventId.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Multiselect.kt
src/commonMain/kotlin/org/cru/godtools/tool/state/State.kt
src/commonTest/kotlin/org/cru/godtools/tool/internal/Channel.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/ContentTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/EventIdTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/MultiselectTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/state/StateTest.kt
src/commonTest/resources/org/cru/godtools/tool/model/multiselect.xml
src/commonTest/resources/org/cru/godtools/tool/model/multiselect_defaults.xml
src/iosMain/kotlin/org/cru/godtools/tool/IosParserConfig.kt

Create a Multiselect model in the shared tool parser. This model can be enabled by adding it to the list of supported features.
```kotlin
ParserConfig.supportedFeatures = setOf(FEATURE_MULTISELECT)
```
Once enabled you can manage the state of the Multiselect model using the following methods:
```kotlin
multiselect.options[0].isSelected(state)
multiselect.options[0].isSelectedFlow(state)
multiselect.options[0].toggleSelected(state)
```
TODO:

GT-1165 Create Multiselect model

---

build.gradle.kts
gradle/libs.versions.toml
src/androidMain/java/org/cru/godtools/tool/model/AndroidColor.kt
src/androidTest/java/org/cru/godtools/tool/model/AndroidColorTest.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Button.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Color.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Manifest.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/PlatformColor.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Styles.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/StylesOverride.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Text.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/lesson/LessonPage.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/tract/CallToAction.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/tract/Card.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/tract/Header.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/tract/TractPage.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/ColorTest.kt
src/iosMain/kotlin/org/cru/godtools/tool/model/IosColor.kt
src/jsMain/kotlin/org/cru/godtools/tool/model/JsColor.kt

Adding support for this library will allow us to more easily define dynamic default colors for tools.
The first use of this will be the default background selected color for multiselect options which will be a lighter version of the current primary color

Utilize colormath library

---

build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/settings.gradle.kts
buildSrc/src/main/kotlin/AndroidConfig.kt
buildSrc/src/main/kotlin/TargetsConfig.kt
buildSrc/src/main/kotlin/VersionUtils.kt
godtools-tool-parser/build.gradle.kts
gradle/libs.versions.toml
settings.gradle.kts

- centralize publishing logic
- centralize the isSnapshotVersion logic into buildSrc
- configure the ios targets via a buildSrc script
- configure the ios background tests in buildSrc
- move js target configuration to buildSrc
- move android target configuration to buildSrc
- enable version catalogs for buildSrc
- extract android config to buildSrc

Extract some common build logic out

---

godtools-tool-parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Multiselect.kt
module/state/src/commonMain/kotlin/org/cru/godtools/tool/state/State.kt
module/state/src/commonTest/kotlin/org/cru/godtools/tool/state/StateTest.kt

- update State.changeFlow to support monitoring multiple keys
- test monitoring multiple keys and monitoring no keys for State.changeFlow
- make `changeFlow` accept a closure to run everytime the monitored keys change

make changeFlow more robust

---

module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/AnalyticsEvent.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Button.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/HasAnalyticsEvents.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Tabs.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/tract/Card.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/tract/Hero.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/ButtonTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/TabsTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/tract/CardTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/tract/HeroTest.kt

models that contain AnalyticsEvents will implement the `HasAnalyticsEvents` interface. This will provide a `model.getAnalyticsEvents(triggerType)` method that will return the events that match the specified trigger type. This method will take any default trigger types defined in the spec into account.

add a HasAnalyticsEvents interface

---

module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/AnalyticsEvent.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Button.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Link.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Tabs.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/ButtonTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/LinkTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/TabsTest.kt

This changes the following usage (which is currently only affects Android):
from: `model.getAnalyticsEvents(SELECTED)` to: `model.getAnalyticsEvents(CLICKED)`

GT-1268 Replace the SELECTED trigger type with CLICKED

---

module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Button.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Input.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Manifest.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Multiselect.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Text.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/lesson/LessonPage.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/tract/CallToAction.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/tract/Card.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/tract/TractPage.kt

This marks several properties as internal when there is a null safe extension property available. on iOS this removes some redundant properties from the GodToolsToolParser framework.
I tested this out locally against godtools-swift and everything still compiles and runs.

Make several properties internal to reduce the API surface

---

module/parser/src/iosTest/kotlin/org/cru/godtools/tool/model/IosColorTest.kt
module/parser/src/jsTest/kotlin/org/cru/godtools/tool/model/JsColorTest.kt

- add an iOS color test that will make sure we are correctly generating an iOS platform color
- add a js test for toPlatformColor()

Add ios & js toPlatformColor tests

---

module/parser/src/commonMain/kotlin/org/cru/godtools/tool/service/ManifestParser.kt

This should hopefully address the immediate symptom of the iOS crash. We still need to figure out the cause to apply a more correct fix long term.

wrap all unhandled exceptions in an Error and log them to Napier

---

build.gradle.kts
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Manifest.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/lesson/Constants.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/lesson/LessonPage.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/page/Constants.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/page/Page.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/ManifestTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/lesson/LessonPageTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/page/PageTest.kt
module/parser/src/commonTest/resources/org/cru/godtools/tool/model/lesson/page_defaults.xml
module/parser/src/commonTest/resources/org/cru/godtools/tool/model/page/page_invalid_namespace.xml
module/parser/src/commonTest/resources/org/cru/godtools/tool/model/page/page_invalid_type.xml

This moves a bunch of common logic to an abstract `Page` model. this `Page` model will be the foundation for various page types across the different tool types.
Dependent on:

GT-1294 Refactor LessonPage logic to extend a shared Page model

---

module/parser/src/commonMain/kotlin/org/cru/godtools/tool/ParserConfig.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Content.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Dimension.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Flow.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/util/Regex.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/ContentTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/DimensionTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/FlowTest.kt
module/parser/src/commonTest/resources/org/cru/godtools/tool/model/flow.xml
module/parser/src/commonTest/resources/org/cru/godtools/tool/model/flow_defaults.xml

Introduces the following new models:
- `Flow`
- has an `items` property that is a list of `Flow.Items` that the flow contains
- has a  `rowGravity` property that defines how each row in the flow should be aligned. This matters when the items in an individual row of the flow don't take up all the horizontal space.
- `Flow.Item`
- provides a `content` list that is to be rendered as children of the item. 
- provides a `width` property that defines how wide this item should be within the containing flow.
There is a new `FEATURE_FLOW` flag that will enable parsing/usage of the new Flow models.

GT-1292 Support parsing a Flow element

---

module/parser/src/commonMain/kotlin/org/cru/godtools/tool/ParserConfig.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Card.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Content.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Manifest.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Styles.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/page/Page.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/tract/Constants.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/tract/TractPage.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/CardTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/ContentTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/tract/TractPageTest.kt
module/parser/src/commonTest/resources/org/cru/godtools/tool/model/card.xml
module/parser/src/commonTest/resources/org/cru/godtools/tool/model/card_defaults.xml
module/parser/src/commonTest/resources/org/cru/godtools/tool/model/manifest_background.xml
module/parser/src/commonTest/resources/org/cru/godtools/tool/model/tract/page_cards.xml

Create the following new model:
- `Card`
- has a `backgroundColor` property that defines the background color of the card
- implements `Clickable` interface so you can make a card clickable to trigger events or open a URL
- implements `Parent` interface because it contains a `content` stack

GT-1338 Parse content cards

---

module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Content.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Flow.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Visibility.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/FlowTest.kt
module/parser/src/commonTest/resources/org/cru/godtools/tool/model/flow_visibility.xml
module/parser/src/iosMain/kotlin/org/cru/godtools/tool/model/IosVisibility.kt

Support `gone-if` and `invisible-if` on Flow Items. This will be used within the updated emoji tool

GT-1403 Parse state visibility attributes on Flow Items

---

module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Multiselect.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Visibility.kt
module/parser/src/iosMain/kotlin/org/cru/godtools/tool/model/IosFlow.kt
module/state/src/commonMain/kotlin/org/cru/godtools/tool/state/State.kt

- don't force distinctUntilChanged on changeFlow
- create a method that will notify a watcher everytime the visible flow items change

Add a watcher for flow items

---

gradle/libs.versions.toml
module/parser/build.gradle.kts
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Gravity.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/GravityTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/TestConstants.kt

- track gravity by the horizontal and vertical component enums
- remove unused START gravity constant
- remove unnecessary bit math logic for tracking the gravity
- make the Gravity constructor visible for testing

Cleanup Gravity class

---

module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Button.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/StylesOverride.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/ButtonTest.kt

This removes the `Styles` interface from the `Button` model. The interface was included as an implementation details to provide default text styles to the child `Text` node. This is no longer necessary due to the `StylesOverride` internal util.
I made sure there was test coverage for all the properties that depended on the `Styles` interface to ensure functionality remained the same after the change.

Don't implement Styles on a Button

---

module/parser/src/androidMain/java/org/cru/godtools/tool/AndroidParserConfig.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/ParserConfig.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Animation.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Card.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Content.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/DeviceType.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Flow.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Manifest.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Multiselect.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/service/ManifestParser.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/AnimationTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/ButtonTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/CardTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/CategoryTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/ContentTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/FallbackTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/FormTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/ImageTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/ManifestTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/MultiselectTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/ParagraphTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/TabsTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/tract/HeroTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/service/ManifestParserTest.kt
module/parser/src/iosMain/kotlin/org/cru/godtools/tool/IosParserConfig.kt
module/parser/src/iosMain/kotlin/org/cru/godtools/tool/service/IosManifestParser.kt
module/parser/src/jsMain/kotlin/org/cru/godtools/tool/JsParserConfig.kt

This moves away from using a `ParserConfig` singleton to instead providing a `ParserConfig` object to the `ManifestParser` service. It is also possible to provide an alternate configuration on a one-off basis when parsing a manifest.
this one-off configuration functionality will be leveraged to provide a mechanism to parse the manifest only and not parse the pages & tips, this will be necessary to enumerate all the associated resources that need to be downloaded for the more granular tool distribution mechanism.

GT-1449 configure parser with ParserConfig instance object

---

module/parser/src/commonMain/kotlin/org/cru/godtools/tool/ParserConfig.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/service/ManifestParser.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/ParserConfigTest.kt
module/parser/src/iosMain/kotlin/org/cru/godtools/tool/service/IosManifestParser.kt

- support a builder pattern for the ParserConfig on iOS
- expose the defaultConfig for a ManifestParser as a property
- don't use default values for ios only logic

Improve iOS interop for new ParserConfig

---

module/parser/src/commonMain/kotlin/org/cru/godtools/tool/ParserConfig.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Manifest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/ParserConfigTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/ManifestTest.kt
module/parser/src/commonTest/resources/org/cru/godtools/tool/model/manifest_related_files.xml

This PR makes it so that a custom config can be provided when parsing a Manifest that will not parse related xml files. It also provides a method that will enumerate all the related files (pages, tips, and resources) for a manifest.

GT-1449 Make it possible to skip parsing pages and tips

---

module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Accordion.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/AccordionTest.kt
module/parser/src/commonTest/resources/org/cru/godtools/tool/model/accordion_analytics.xml

This PR adds the `HasAnalyticsEvents` interface to Accordion sections. This provides a `getAnalyticsEvents(triggerType)` method on the accordion section that will allow you to access any analytics events that need to be fired for a specific Trigger type.

GT-1606 Support parsing Analytics events on Accordion Sections

---

module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Manifest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/ManifestTest.kt

this property will return whether a manifest has tips or not, even if those tips have not been parsed

introduce a hasTips property to the Manifest

---

src/iosMain/kotlin/org/cru/godtools/tool/napier/NapierProxy.kt

Provides the following swift headers:
```swift
public class NapierProxyKt : KotlinBase {
open class func enableCustomLogging(onLog: @escaping (NapierLogLevel, String?, KotlinThrowable?, String?) -> Void)
open class func enableDebugLogging()
}
public class NapierLogLevel : KotlinEnum<NapierLogLevel> {
open class var verbose: NapierLogLevel { get }
open class var debug: NapierLogLevel { get }
open class var info: NapierLogLevel { get }
open class var warning: NapierLogLevel { get }
open class var error: NapierLogLevel { get }
open class var assert: NapierLogLevel { get }
open class func values() -> KotlinArray<NapierLogLevel>
}
```

GT-1358 Provide Napier glue logic for iOS

---

module/parser/src/commonMain/kotlin/org/cru/godtools/tool/ParserConfig.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Animation.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Card.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Content.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Flow.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Multiselect.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Version.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/ParserConfigTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/ContentTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/VersionTest.kt
module/parser/src/commonTest/resources/org/cru/godtools/tool/model/content_required_versions.xml
module/parser/src/commonTest/resources/org/cru/godtools/tool/model/content_required_versions_invalid.xml

This PR adds support for new `required-android-version` and `required-ios-version` attributes on content elements. This will allow new features to be hidden on specific versions of the mobile apps

GT-1569 Support required-android-version and required-ios-version content attributes

---

gradle.properties
module/parser/src/androidMain/java/org/cru/godtools/tool/AndroidParserConfig.kt
module/parser/src/androidMain/kotlin/org/cru/godtools/tool/model/AndroidDeviceType.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/ParserConfig.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Content.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/DeviceType.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/ParserConfig+Fixtures.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/ParserConfigTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/AnimationTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/ButtonTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/CardTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/ContentTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/FormTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/ImageTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/MultiselectTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/ParagraphTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/TabsTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/tract/HeroTest.kt
module/parser/src/commonTest/resources/org/cru/godtools/tool/model/content_required_device_type.xml
module/parser/src/commonTest/resources/org/cru/godtools/tool/model/content_restrict_to.xml
module/parser/src/iosMain/kotlin/org/cru/godtools/tool/IosParserConfig.kt
module/parser/src/iosMain/kotlin/org/cru/godtools/tool/model/IosDeviceType.kt
module/parser/src/jsMain/kotlin/org/cru/godtools/tool/JsParserConfig.kt
module/parser/src/jsMain/kotlin/org/cru/godtools/tool/model/JsDeviceType.kt

- define DeviceType.DEFAULT to be automatically set based on which language is consuming this library
- replace supportedDeviceTypes with the singular deviceType property on ParserConfig
- make ParserConfig constructor private
- make the DeviceType optional for withAppVersion()
- rename restrictTo property to requireDeviceType
- add support for parsing required-device-type xml attribute

GT-1569 rename restrictTo to required-device-type

---

module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/ContentTest.kt

also, don't require the flow to complete because that is an implementation detail and not part of the expected method contract

restore updating state properties for isGoneFlow and isInvisibleFlow tests

---

buildSrc/src/main/kotlin/TargetsConfig.kt
gradle.properties
gradle/libs.versions.toml
module/parser/build.gradle.kts
module/parser/src/jsTest/kotlin/org/cru/godtools/shared/tool/parser/internal/UsesResources.js.kt

This switches from the legacy Kotlin/JS compiler to the new IR Kotlin/JS compiler. This was one of the things blocking us from using this library on knowgod.com

enable IR for Kotlin/JS

---

build.gradle.kts
module/analytics/build.gradle.kts
module/analytics/src/commonMain/kotlin/org/cru/godtools/shared/analytics/AnalyticsActionNames.kt
module/analytics/src/commonMain/kotlin/org/cru/godtools/shared/analytics/AnalyticsAppSectionNames.kt
module/analytics/src/commonMain/kotlin/org/cru/godtools/shared/analytics/AnalyticsScreenNames.kt
module/analytics/src/commonTest/kotlin/org/cru/godtools/shared/analytics/AnalyticsAppSectionNamesTest.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/analytics/ToolAnalyticsScreenNames.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/page/CardCollectionPage.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/tips/TipPage.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/tract/TractPage.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/analytics/ToolAnalyticsScreenNamesTest.kt
settings.gradle.kts

This provides several objects that can be used to get analytics screen names for most screens. This is just a start and doesn't cover all screen and events yet.

Centralize several Analytics constants to share between iOS and Android

---

gradle/libs.versions.toml
module/common/build.gradle.kts
module/common/src/androidMain/kotlin/org/cru/godtools/shared/common/model/PlatformColor.android.kt
module/common/src/commonMain/kotlin/org/cru/godtools/shared/common/model/PlatformColor.kt
module/common/src/commonMain/kotlin/org/cru/godtools/shared/common/model/ThemeType.kt
module/common/src/iosMain/kotlin/org/cru/godtools/shared/common/internal/colormath/Color.kt
module/common/src/iosMain/kotlin/org/cru/godtools/shared/common/model/PlatformColor.ios.kt
module/common/src/jsMain/kotlin/org/cru/godtools/shared/common/model/PlatformColor.js.kt
module/parser/src/iosMain/kotlin/org/cru/godtools/shared/tool/parser/model/PlatformColor.ios.kt
module/user-activity/build.gradle.kts
module/user-activity/src/androidMain/kotlin/org/cru/godtools/shared/user/activity/model/IconColors.android.kt
module/user-activity/src/commonMain/kotlin/org/cru/godtools/shared/user/activity/model/Badge.kt
module/user-activity/src/commonMain/kotlin/org/cru/godtools/shared/user/activity/model/IconColors.kt
module/user-activity/src/commonMain/kotlin/org/cru/godtools/shared/user/activity/model/UserActivity.kt
module/user-activity/src/commonTest/kotlin/org/cru/godtools/shared/user/activity/internal/test/Assertions.kt
module/user-activity/src/commonTest/kotlin/org/cru/godtools/shared/user/activity/model/BadgeTest.kt
module/user-activity/src/commonTest/kotlin/org/cru/godtools/shared/user/activity/model/BadgeTypeTest.kt
module/user-activity/src/commonTest/kotlin/org/cru/godtools/shared/user/activity/model/IconColorsTest.kt
module/user-activity/src/commonTest/kotlin/org/cru/godtools/shared/user/activity/model/UserActivityColorsTest.kt
module/user-activity/src/iosMain/kotlin/org/cru/godtools/shared/user/activity/model/IconColors.ios.kt
settings.gradle.kts

Update User Activity models to expose icon colors to use when coloring the various activity & badge icons.
on iOS they should be access like this:
```swift
UserActivity.Colors.shared.toolOpens.color(mode: .light)
UserActivity.Colors.shared.toolOpens.containerColor(mode: .light)
let userActivity = UserActivity()
userActivity.badge.colors.color(mode: .light)
userActivity.badge.colors.containerColor(mode: .light)
```

GT-1866 Define user activity colors centrally

---

module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/AnalyticsEvent.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/AnalyticsEventTest.kt
module/parser/src/commonTest/resources/org/cru/godtools/shared/tool/parser/model/analytics_event.xml
module/parser/src/commonTest/resources/org/cru/godtools/shared/tool/parser/model/analytics_event_defaults.xml
module/parser/src/commonTest/resources/org/cru/godtools/shared/tool/parser/model/analytics_events.xml
module/state/src/commonMain/kotlin/org/cru/godtools/shared/tool/state/State.kt
module/state/src/commonTest/kotlin/org/cru/godtools/shared/tool/state/StateTest.kt

This supports a new `limit` attribute for analytics events in the content xml. To enforce this limit a consumer will use `shouldTrigger(state)` and `recordTriggered(state)` on the AnalyticsEvent.
Data about if the limit has been reached will be recorded in the `State` object.

GT-1909 Support parsing & enforcing a limit on AnalyticsEvents

---

module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/ManifestParser.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/ManifestParserTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/internal/CapturingAntilog.kt

Another place we weren't correctly propagating CancellationExceptions

GT-1957 Correctly handle CancellationExceptions in ManifestParser

---

module/parser/src/jsMain/kotlin/org/cru/godtools/shared/tool/parser/xml/JsXmlPullParserFactory.kt
module/parser/src/jsTest/kotlin/org/cru/godtools/shared/tool/parser/internal/UsesResources.js.kt

Updated Typescript header:
```typescript
export declare namespace org.cru.godtools.shared.tool.parser.xml {
abstract class JsXmlPullParserFactory extends org.cru.godtools.shared.tool.parser.xml.XmlPullParserFactory {
constructor();
abstract readFile(fileName: string): Promise<Nullable<string>>;
}
}
```

GT-1922 update JsXmlPullParserFactory.readFile() to return a Promise

---

module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/ManifestParser.kt

default parameters don't export to iOS or js at all, so we will avoid using them here

Don't rely on Kotlin default parameters for parseManifest

---

publishing/npm/build.gradle.kts

Gradle 8 requires task dependencies to be correctly declared, which is causing the npm-publish plugin to fail because it depended on files from the `kotlinNodeJsSetup` task without declaring a dependency on the task.
Upstream bug report: https://github.com/mpetuska/npm-publish/issues/110

Workaround a fatal npm-publish task dependency issue

---

module/state/src/commonMain/kotlin/org/cru/godtools/shared/tool/state/State.kt

Updated Typescript Headers:
```typescript
export declare namespace org.cru.godtools.shared.tool.state {
class State /* implements org.cru.godtools.shared.tool.state.internal.Parcelable */ {
private constructor();
static createState(): org.cru.godtools.shared.tool.state.State;
}
}
```

GT-1922 Don't export State members to TypeScript

---

module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/ParserConfig.kt

Updated Typescript Headers:
```typescript
export declare namespace org.cru.godtools.shared.tool.parser {
class ParserConfig {
private constructor();
static createParserConfig(): org.cru.godtools.shared.tool.parser.ParserConfig;
withSupportedFeatures(features: any/* kotlin.collections.Set<string> */): org.cru.godtools.shared.tool.parser.ParserConfig;
withParseRelated(enabled: boolean): org.cru.godtools.shared.tool.parser.ParserConfig;
withParsePages(enabled: boolean): org.cru.godtools.shared.tool.parser.ParserConfig;
withParseTips(enabled: boolean): org.cru.godtools.shared.tool.parser.ParserConfig;
copy(deviceType?: any/* org.cru.godtools.shared.tool.parser.model.DeviceType */, appVersion?: Nullable<any>/* Nullable<org.cru.godtools.shared.tool.parser.model.Version> */, supportedFeatures?: …
```

GT-1922 Hide ParserConfig.withAppVersion() from Typescript

---

module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/ManifestParser.kt

Updated header:
```typescript
export declare namespace org.cru.godtools.shared.tool.parser {
abstract class ParserResult {
protected constructor();
}
namespace ParserResult {
class Data extends org.cru.godtools.shared.tool.parser.ParserResult {
constructor(manifest: any/* org.cru.godtools.shared.tool.parser.model.Manifest */);
get manifest(): any/* org.cru.godtools.shared.tool.parser.model.Manifest */;
}
class ParserError extends org.cru.godtools.shared.tool.parser.ParserResult {
constructor(error?: Nullable<Error>);
get error(): Nullable<Error>;
}
namespace ParserError {
class Corrupted extends org.cru.godtools.shared.tool.parser.ParserResult.ParserError {
private constructor();
}
class NotFound extends org.cru.godtools.shared.tool.parser.ParserResult.ParserError {
private constructor(); …
```

GT-1922 The generated TypeScript headers won't allow a class with an internal constructor to be extended

---

module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/ParserConfig.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/ParserConfigTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/AnimationTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/ButtonTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/CardTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/ContentTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/MultiselectTest.kt

this version will be used for TypeScript and Android. iOS doesn't provide a clean interop with vararg parameters unfortunately
Updated TypeScript headers:
```typescript
export declare namespace org.cru.godtools.shared.tool.parser {
class ParserConfig {
private constructor();
static createParserConfig(): org.cru.godtools.shared.tool.parser.ParserConfig;
withSupportedFeatures(feature: Array<string>): org.cru.godtools.shared.tool.parser.ParserConfig;
withParseRelated(enabled: boolean): org.cru.godtools.shared.tool.parser.ParserConfig;
withParsePages(enabled: boolean): org.cru.godtools.shared.tool.parser.ParserConfig;
withParseTips(enabled: boolean): org.cru.godtools.shared.tool.parser.ParserConfig;
copy(deviceType?: any/* org.cru.godtools.shared.tool.parser.model.DeviceType */, appVersion?: …
```

GT-1922 introduce a vararg version of withSupportedFeatures()

---

module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/AnalyticsEvent.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Button.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Link.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Tabs.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/tract/Hero.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/tract/TractPage.kt

Hide direct access to AnalyticsEvents for model objects

---

module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Clickable.kt

- export the Clickable type to TypeScript
- expose Clickable.events as an Array in TypeScript

GT-1922 Expose the Clickable type to TypeScript

---

module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/tips/InlineTip.kt

I'm exporting this because it will be returned as a possible content object, but it is not necessary to render anything for this content object

GT-1922 export InlineTip type to TypeScript

---

module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Multiselect.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/MultiselectTest.kt

- Multiselect.Option does not need to extend the Content type
- expose any nested tips under a multi-select

Adjust Multiselect.Option type

---

module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Animation.kt

in order for Animations to actually show up in the object model, you need to enable support for them in the ParserConfig. I can't remember if we previously had Animation support on knowgod.com or not, if we didn't you can wait until we finish transitioning to the parser to enable animations and create the renderer for them.

GT-1922 export the Animation type to TypeScript

---

module/parser/src/androidMain/kotlin/org/cru/godtools/shared/tool/parser/model/Card.android.kt
module/parser/src/androidUnitTest/kotlin/org/cru/godtools/shared/tool/parser/model/AndroidCardTest.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Card.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/CardTest.kt

- make Card?.backgroundColor extension method Android only
- expose the Card type to TypeScript

GT-1922 expose the Card type to TypeScript

---

module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/analytics/ToolAnalyticsActionNames.kt

Added a new `ACTION_SETTINGS` analytics constant for when the user clicks the icon to open tool settings.
I also imported a bunch of other tool action constants from Android that we hadn't moved to our shared module yet

GT-1833 GT-2024 Tool Actions Analytics constants

---

module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/AnalyticsEvent.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/AnalyticsEventTest.kt

Events targeting these systems have no need to fallback and be redirected to other analytics systems, so we don't care if they are correctly parsed

GT-1534 We don't need to parse AppsFlyer or Snowplow analytics event systems

---

.github/workflows/build.yml
gradle.properties

This fixes an incompatibility between Kotlin 1.9 and AGP 8.0.x

Temporarily override the android lint version

---

module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Text.kt

There is no need for Text.text to be nullable

make Text.text non-null

---

module/common/build.gradle.kts
module/common/src/androidMain/kotlin/org/cru/godtools/shared/common/model/Uri.android.kt
module/common/src/commonMain/kotlin/org/cru/godtools/shared/common/model/Uri.kt
module/common/src/commonTest/kotlin/org/cru/godtools/shared/common/model/UriTest.kt
module/common/src/iosMain/kotlin/org/cru/godtools/shared/common/model/Uri.ios.kt
module/common/src/jsMain/kotlin/org/cru/godtools/shared/common/model/Uri.js.kt
module/parser/src/androidMain/kotlin/org/cru/godtools/shared/tool/parser/util/Uri.android.kt
module/parser/src/androidUnitTest/kotlin/org/cru/godtools/shared/tool/parser/model/TestConstants.android.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Manifest.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/util/Uri.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/util/UriTest.kt
module/parser/src/iosMain/kotlin/org/cru/godtools/shared/tool/parser/util/Uri.ios.kt
module/parser/src/jsMain/kotlin/org/cru/godtools/shared/tool/parser/util/Uri.js.kt

- **relocate Uri.scheme property to the common module**
- **make toUriOrNull take a non-null receiver**
- **use a String for Uris on Android**

Update the Uri actual for Android in preparation for Kotlin 2

---

module/user-activity/src/commonMain/kotlin/org/cru/godtools/shared/user/activity/UserCounterNames.kt
module/user-activity/src/commonTest/kotlin/org/cru/godtools/shared/user/activity/UserCounterNamesTest.kt

This will allow us to generate the name for lesson completion counters in a manner that will be consistent on all platforms

add a UserCounterName for lesson completion counters

---

module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/ParserConfig.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/HasPages.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Manifest.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/lesson/LessonPage.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/page/CardCollectionPage.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/page/ContentPage.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/page/Page.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/page/PageCollectionPage.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/tract/TractPage.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/analytics/ToolAnalyticsScreenNamesTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/internal/UsesResources.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/ManifestTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/page/PageCollectionPageTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/page/PageTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/tract/TractPageTest.kt
module/parser/src/commonTest/resources/org/cru/godtools/shared/tool/parser/model/page/page_content.xml
module/parser/src/commonTest/resources/org/cru/godtools/shared/tool/parser/model/page/page_content_parent.xml
module/parser/src/commonTest/resources/org/cru/godtools/shared/tool/parser/model/page/page_content_parent_override.xml
module/parser/src/commonTest/resources/org/cru/godtools/shared/tool/parser/model/page/page_page-collection.xml
module/parser/src/commonTest/resources/org/cru/godtools/shared/tool/parser/model/page/page_page-collection_imports.xml

This adds support for parsing the new page collection page type for CYOA tools. This functionality is behind a new `FEATURE_PAGE_COLLECTION` feature flag that can be enabled when you are ready to use the functionality.
a `PageCollectionPage` contains a list of pages that should be rendered as a swipeable view pager.
TODO:

GT-2450 Add support for PageCollectionPages in CYOA tools

---

module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Accordion.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Animation.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Clickable.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Flow.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/HasAnalyticsEvents.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/HasPages.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Manifest.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Multiselect.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Parent.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Tabs.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Text.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/page/Page.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/tract/Modal.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/tract/TractPage.kt

This PR hides several properties that expose kotlin collections in favor of the already exposed JS Array variants

TypeScript export updates

---

module/parser/src/androidMain/kotlin/org/cru/godtools/shared/tool/parser/xml/AndroidXmlPullParser.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Animation.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Content.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Manifest.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Resource.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/tips/InlineTip.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/tips/Tip.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/tract/TractPage.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/xml/SaxXmlPullParser.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/xml/XmlPullParser.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/xml/XmlPullParserTest.kt
module/parser/src/commonTest/resources/org/cru/godtools/shared/tool/parser/xml/parser_attributes_namespaces.xml

- **add a unit test for the broken Android attribute parsing**
- **update AndroidXmlPullParser to use "" for the namespace when the attribute doesn't have a namespace**
- **make the namespace for getAttributeValue non-null**

GT-2538 Fix Attribute parsing on Android

---

.github/workflows/build.yml
build-logic/src/main/kotlin/TargetsConfig.kt

This is no longer relevant after switching to the new memory model for iOS

remove ios background test task

---

module/renderer/src/commonMain/kotlin/org/cru/godtools/shared/renderer/content/RenderAnimation.kt
module/renderer/src/commonMain/kotlin/org/cru/godtools/shared/renderer/content/RenderTabs.kt
module/renderer/src/commonMain/kotlin/org/cru/godtools/shared/renderer/util/ContentEventListener.kt

I found myself looking to repeat this logic again for another listener in lesson pages, so decided to create a shared composable to handle the core logic

GT-2694 Add a HandleContentEvents composable to standardize logic
