src/androidMain/java/org/cru/godtools/tool/model/AndroidUri.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Button.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Content.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Manifest.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Styles.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Uri.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/ButtonTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/ContentTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/StylesTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/UriTest.kt
src/commonTest/resources/org/cru/godtools/tool/model/button_event.xml
src/commonTest/resources/org/cru/godtools/tool/model/button_restrictTo.xml
src/commonTest/resources/org/cru/godtools/tool/model/button_url.xml
src/iosMain/kotlin/org/cru/godtools/tool/model/IosUri.kt
src/jsMain/kotlin/org/cru/godtools/tool/model/JsUri.kt

- add support for parsing Button Types and Styles
- support parsing most of the button attributes
TODO:

Button Model

---

src/commonMain/kotlin/org/cru/godtools/tool/model/Content.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Form.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Image.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/AccordionTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/ContentTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/FormTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/ImageTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/ParagraphTest.kt
src/commonTest/resources/org/cru/godtools/tool/model/form.xml
src/commonTest/resources/org/cru/godtools/tool/model/form_ignored_content.xml
src/commonTest/resources/org/cru/godtools/tool/model/image.xml
src/commonTest/resources/org/cru/godtools/tool/model/image_restricted.xml

- add support for parsing Image elements
- enable some tests that rely on the Image content model
- add support for parsing Form elements

Add several more Content models

---

src/commonMain/kotlin/org/cru/godtools/tool/model/Manifest.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/tips/Constants.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/tips/Tip.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/tips/TipPage.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/ManifestTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/tips/TipTest.kt
src/commonTest/resources/org/cru/godtools/tool/model/tips/tip.xml
src/commonTest/resources/org/cru/godtools/tool/model/tips/tip_defaults.xml

- add intial support for parsing a tip
- parse tips included in a Manifest
- support parsing tip pages

Support parsing tips

---

src/commonMain/kotlin/org/cru/godtools/tool/model/Content.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Input.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Link.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Manifest.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Spacer.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Video.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/tips/InlineTip.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/ContentTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/InputTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/LinkTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/SpacerTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/VideoTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/tips/InlineTipTest.kt
src/commonTest/resources/org/cru/godtools/tool/model/input_email.xml
src/commonTest/resources/org/cru/godtools/tool/model/input_hidden.xml
src/commonTest/resources/org/cru/godtools/tool/model/input_text.xml
src/commonTest/resources/org/cru/godtools/tool/model/link.xml
src/commonTest/resources/org/cru/godtools/tool/model/spacer.xml
src/commonTest/resources/org/cru/godtools/tool/model/spacer_fixed.xml
src/commonTest/resources/org/cru/godtools/tool/model/tips/inline_tip.xml
src/commonTest/resources/org/cru/godtools/tool/model/video.xml

- add support for parsing inline tips
- add support for parsing Input elements
- add support for parsing Link content elements
- add support for parsing Spacer elements

More Content Models

---

src/commonMain/kotlin/org/cru/godtools/tool/model/Animation.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Button.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Category.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Content.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/DeviceType.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Image.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Input.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Manifest.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Spacer.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Text.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Video.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/tips/InlineTip.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/tips/TipPage.kt
src/iosMain/kotlin/org/cru/godtools/tool/model/IosColor.kt

- mark several companion objects as internal
- mark the color function as an internal function

Cleanup the API surface for iOS

---

src/commonMain/kotlin/org/cru/godtools/tool/model/Base.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/ImageGravity.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Text.kt

- expose the manifest extension method
- make it possible to create a Text object for tests outside of this library

Minor tweaks

---

src/commonMain/kotlin/org/cru/godtools/tool/model/Button.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/ButtonTest.kt

Implement the default button text-color behavior based on the content spec located here:
https://github.com/CruGlobal/mobile-content-api/blob/168cbeaed59bf01b92cbb1a80857ac193d35bdd0/public/xmlns/content.xsd#L479-L505

Implement button text color behavior

---

src/commonMain/kotlin/org/cru/godtools/tool/model/Link.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/LinkTest.kt

Implement the default text-color for links per the specification:
https://github.com/CruGlobal/mobile-content-api/blob/168cbeaed59bf01b92cbb1a80857ac193d35bdd0/public/xmlns/content.xsd#L532-L536

Link text-color

---

src/androidMain/java/org/cru/godtools/tool/xml/AndroidXmlPullParserFactory.kt
src/androidTest/java/org/cru/godtools/tool/internal/-AndroidTestingPlatform.kt
src/commonMain/kotlin/org/cru/godtools/tool/xml/XmlPullParserFactory.kt
src/commonTest/kotlin/org/cru/godtools/tool/internal/-CommonTestingPlatform.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/AccordionTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/AnalyticsEventTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/AnimationTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/ButtonTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/ContentTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/FallbackTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/FormTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/ImageTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/InputTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/LinkTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/ParagraphTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/SpacerTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/TabsTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/TextTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/VideoTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/lesson/LessonPageTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/tips/InlineTipTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/tips/TipTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/tract/CallToActionTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/tract/CardTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/tract/HeaderTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/tract/HeroTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/tract/ModalTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/tract/TractPageTest.kt
src/iosMain/kotlin/org/cru/godtools/tool/xml/IosXmlPullParserFactory.kt
src/jsMain/kotlin/org/cru/godtools/tool/xml/JsXmlPullParserFactory.kt

- update getTestXmlParser to be suspending
- make AndroidXmlPullParserFactory.openFile suspendable

Make AndroidXmlPullParserFactory support coroutines

---

src/commonMain/kotlin/org/cru/godtools/tool/model/ImageGravity.kt

it seems that value classes aren't supported on iOS yet

make ImageGravity a normal class

---

src/commonMain/kotlin/org/cru/godtools/tool/internal/-CommonPlatform.kt
src/commonMain/kotlin/org/cru/godtools/tool/service/ManifestParser.kt
src/iosMain/kotlin/org/cru/godtools/tool/internal/-IosPlatform.kt
src/jsMain/kotlin/org/cru/godtools/tool/internal/-JsPlatform.kt

- include the thrown exception on error results
- record the fileName for FileNotFoundExceptions

Improve Error Result responses

---

src/commonMain/kotlin/org/cru/godtools/tool/model/Manifest.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Multiselect.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/PlatformColor.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/Styles.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/lesson/LessonPage.kt
src/commonMain/kotlin/org/cru/godtools/tool/model/tract/TractPage.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/ManifestTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/MultiselectTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/StylesTest.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/TestColors.kt
src/commonTest/kotlin/org/cru/godtools/tool/model/lesson/LessonPageTest.kt
src/commonTest/resources/org/cru/godtools/tool/model/lesson/page.xml
src/commonTest/resources/org/cru/godtools/tool/model/manifest_lesson.xml
src/commonTest/resources/org/cru/godtools/tool/model/multiselect.xml

This PR adds support for defining a background color and selected color for multiselect options

Add background color support to Multiselect Options

---

godtools-tool-parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Constants.kt
godtools-tool-parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Content.kt
godtools-tool-parser/src/commonTest/kotlin/org/cru/godtools/tool/model/ButtonTest.kt
godtools-tool-parser/src/commonTest/kotlin/org/cru/godtools/tool/model/ContentTest.kt
godtools-tool-parser/src/commonTest/resources/org/cru/godtools/tool/model/button_event.xml
godtools-tool-parser/src/commonTest/resources/org/cru/godtools/tool/model/button_requiredFeatures.xml

GT-1234 Support parsing required-features content restrictions

---

godtools-tool-parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Button.kt
godtools-tool-parser/src/commonMain/kotlin/org/cru/godtools/tool/model/ImageGravity.kt
godtools-tool-parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Resource.kt
godtools-tool-parser/src/commonTest/kotlin/org/cru/godtools/tool/model/ButtonTest.kt
godtools-tool-parser/src/commonTest/resources/org/cru/godtools/tool/model/button_icon.xml

GT-1136 Support parsing button icons

---

build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/AntlrConfig.kt
module/expressions/build.gradle.kts
module/expressions/src/commonMain/antlr/org/cru/godtools/expressions/grammar/generated/StateExpression.g4
module/expressions/src/commonMain/kotlin/org/cru/godtools/expressions/Expression.kt
module/expressions/src/commonMain/kotlin/org/cru/godtools/expressions/grammar/StateExpressionEvaluator.kt
settings.gradle.kts

- include the antlr-kotlin gradle plugin in buildSrc dependencies
- utilize buildSrc to configure antlr-kotlin

Update antlr-kotlin builds to fix hanging IDE

---

module/expressions/src/commonMain/antlr/org/cru/godtools/expressions/grammar/generated/StateExpression.g4
module/expressions/src/commonMain/kotlin/org/cru/godtools/expressions/Expression.kt
module/expressions/src/commonMain/kotlin/org/cru/godtools/expressions/grammar/StateExpressionEvaluator.kt
module/expressions/src/commonTest/kotlin/org/cru/godtools/expressions/ExpressionTest.kt

- make it possible to evaluate both boolean and int expressions with StateExpressionEvaluator
- add support for comparing int values
- add an expression function that will return the number of values set to a state var

GT-1239 Support testing the number of values set to a state var

---

module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/lesson/LessonPage.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/lesson/LessonPageTest.kt
module/parser/src/commonTest/resources/org/cru/godtools/tool/model/lesson/page.xml

GT-1278 Support parsing analytics events on a LessonPage

---

module/parser/src/androidTest/java/org/cru/godtools/tool/model/AndroidTestConstants.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Button.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Clickable.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Image.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Link.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/ButtonTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/ImageTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/LinkTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/TestConstants.kt
module/parser/src/iosTest/kotlin/org/cru/godtools/tool/model/IosTestConstants.kt
module/parser/src/jsTest/kotlin/org/cru/godtools/tool/model/JsTestConstants.kt

- create a new Clickable interface
- update Button, Link, Image to implement the Clickable interface
- ignore buttons and links that aren't clickable
- ignore images that don't have a resourceName set

GT-980 Support URLs for links

---

module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/page/CardCollectionPage.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/page/Page.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/page/CardCollectionPageTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/page/PageTest.kt
module/parser/src/commonTest/resources/org/cru/godtools/tool/model/page/page_cardcollection.xml

- add initial support for parsing card collection pages
- add support for parsing cards in a card collection page

GT-1294 Add support for parsing Card Collection pages

---

module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Button.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Image.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/ButtonTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/ImageTest.kt
module/parser/src/commonTest/resources/org/cru/godtools/tool/model/button_event.xml
module/parser/src/commonTest/resources/org/cru/godtools/tool/model/image_attrs.xml
module/parser/src/commonTest/resources/org/cru/godtools/tool/model/image_width_full.xml
module/parser/src/commonTest/resources/org/cru/godtools/tool/model/image_width_invalid.xml

Support parsing `width` and `gravity` for Images and Buttons.
Related Spec PR: https://github.com/CruGlobal/mobile-content-api/pull/829

GT-1291 Support parsing fixed width images and buttons

---

module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/AnalyticsEvent.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/AnalyticsEventTest.kt

- support parsing the user analytics system
- add a deprecation note for the ADOBE analytics system
- add unit test for parsing user analytics system

GT-1382 Add User analytics system

---

module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/AspectRatio.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Video.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/AspectRatioTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/VideoTest.kt
module/parser/src/commonTest/resources/org/cru/godtools/tool/model/video.xml
module/parser/src/commonTest/resources/org/cru/godtools/tool/model/video_defaults.xml

- create an AspectRatio model
- add support for parsing video aspect-ratio, width, and gravity

GT-1438 Support parsing video aspect-ratio

---

.github/workflows/build.yml
buildSrc/src/main/kotlin/TargetsConfig.kt
gradle.properties

ios target adjustments

---

module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Manifest.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/shareable/Shareable.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/shareable/ShareableImage.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/ManifestTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/shareable/ShareableImageTest.kt
module/parser/src/commonTest/resources/org/cru/godtools/tool/model/manifest_shareables.xml
module/parser/src/commonTest/resources/org/cru/godtools/tool/model/shareable/shareable_image.xml

- description is now part of ShareableImage only
- support parsing an order for Shareables

GT-1436 Adjustments to the Shareables model

---

module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Clickable.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/tool/model/Uri.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/tool/model/UriTest.kt

- add some unit tests for the godtools URI scheme
- rename a few parsing method to better reflect that they are just fixing the scheme

Make some minor tweaks to uri parsing

---

module/user-activity/src/commonMain/kotlin/org/cru/godtools/shared/user/activity/model/Badge.kt
module/user-activity/src/commonTest/kotlin/org/cru/godtools/shared/user/activity/model/BadgeTest.kt
module/user-activity/src/commonTest/kotlin/org/cru/godtools/shared/user/activity/model/BadgeTypeTest.kt
module/user-activity/src/commonTest/kotlin/org/cru/godtools/shared/user/activity/model/UserActivityTest.kt

This will be useful when selecting out the icon to use for a badge

GT-1866 Expose a property that indicates which variant a badge is

---

gradle/libs.versions.toml
module/parser/build.gradle.kts
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/ManifestParser.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/ParserConfig.kt
settings.gradle.kts

new Typescript types:
```typescript
export declare class ManifestParser {
constructor(parserFactory: org.cru.godtools.shared.tool.parser.xml.XmlPullParserFactory, defaultConfig: org.cru.godtools.shared.tool.parser.ParserConfig);
get defaultConfig(): org.cru.godtools.shared.tool.parser.ParserConfig;
parseManifest(fileName: string, config: org.cru.godtools.shared.tool.parser.ParserConfig, abortSignal: AbortSignal): Promise<org.cru.godtools.shared.tool.parser.ParserResult>;
}
export declare namespace org.cru.godtools.shared.tool.parser {
abstract class ParserResult {
protected constructor();
}
namespace ParserResult {
class Data extends org.cru.godtools.shared.tool.parser.ParserResult {
constructor(manifest: any/* org.cru.godtools.shared.tool.parser.model.Manifest */);
get manifest(): any/* …
```

GT-1922 Expose the ManifestParser to Typescript

---

module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Dimension.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/PlatformColor.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/lesson/Constants.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/page/Constants.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/EventIdTest.kt

this is no longer needed with the new memory model

remove deprecated SharedImmutable annotation

---

module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/AnalyticsEvent.kt
module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Button.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/AnalyticsEventTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/ButtonTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/LinkTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/MultiselectTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/TabsTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/lesson/LessonPageTest.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/tract/TractPageCardTest.kt

- **remove deprecated Trigger.SELECTED for AnalyticsEvents**
- **remove deprecated Adobe analytics system**

Remove some deprecated code

---

build-logic/build.gradle.kts
build-logic/src/main/kotlin/org/cru/godtools/shared/gradle/KotlinAntlrExtension.kt
build-logic/src/main/kotlin/org/cru/godtools/shared/gradle/KotlinAntlrPlugin.kt
gradle/libs.versions.toml
module/parser-expressions/build.gradle.kts
module/parser-expressions/src/commonMain/antlr/org/cru/godtools/shared/tool/parser/expressions/grammar/generated/StateExpression.g4
module/parser-expressions/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/expressions/Expression.kt
module/parser-expressions/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/expressions/grammar/StateExpressionEvaluator.kt

- switch to the official antlr-kotlin release
- update our KotlinAntlrPlugin for official version of antlr-kotlin
- update parser-expressions to use the main release of antlr-kotlin

Switch to main antlr-kotlin plugin

---

build.gradle.kts

GT-2047 try building the XCFramework as a dynamic framework

---

module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/page/CardCollectionPage.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/page/CardCollectionPageTest.kt
module/parser/src/commonTest/resources/org/cru/godtools/shared/tool/parser/model/page/page_cardcollection.xml
module/parser/src/commonTest/resources/org/cru/godtools/shared/tool/parser/model/page/page_cardcollection_defaults.xml

Dependent on: https://github.com/CruGlobal/mobile-content-api/pull/1779

GT-2573 Add support for an optional Header on CardCollectionPages

---

.github/workflows/build.yml
build-logic/build.gradle.kts
build-logic/src/main/kotlin/KtlintConfiguration.kt
build-logic/src/main/kotlin/Project.kt
build-logic/src/main/kotlin/TargetsConfig.kt
build-logic/src/main/kotlin/godtools-shared.module-conventions.gradle.kts
build-logic/src/main/kotlin/org/cru/godtools/shared/gradle/KotlinAntlrExtension.kt
build.gradle.kts
gradle/libs.versions.toml

- **enable ktlint for build-logic**
- **move the ktlint configuration to build-logic**

Update the ktlint configuration

---

module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Text.kt
module/parser/src/commonTest/kotlin/org/cru/godtools/shared/tool/parser/model/TextTest.kt
module/parser/src/commonTest/resources/org/cru/godtools/shared/tool/parser/model/text_device_overrides.xml

Dependent on: https://github.com/CruGlobal/mobile-content-api/pull/1784

GT-2585 Add additional device overrides for text attributes

---

module/renderer/src/commonMain/kotlin/org/cru/godtools/shared/renderer/content/RenderContentStack.kt
module/renderer/src/iosMain/kotlin/org/cru/godtools/shared/renderer/content/ContentStackView.kt

- **enable vertical scroll for a content stack**
- **support passing in state from iOS for rendering a ContentStack**

GT-2484 Adjust the integration for iOS

---

module/renderer/src/androidUnitTest/kotlin/org/cru/godtools/shared/renderer/content/RenderTextPaparazziTest.kt
module/renderer/src/commonMain/kotlin/org/cru/godtools/shared/renderer/content/RenderText.kt
module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderTextPaparazziTest_RenderText()_-_Minimum_Lines.png
module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderTextPaparazziTest_RenderText()_-_Text_Scale.png

Hey @frett how does the default font size of 18.sp sound?  That too large?  It will effect the paparazzi images.

GT-2646 support missing properties on text elements

---

module/parser/src/commonMain/kotlin/org/cru/godtools/shared/tool/parser/model/Tabs.kt
module/renderer/src/androidUnitTest/kotlin/org/cru/godtools/shared/renderer/content/RenderTabsPaparazziTest.kt
module/renderer/src/commonMain/kotlin/org/cru/godtools/shared/renderer/content/RenderContent.kt
module/renderer/src/commonMain/kotlin/org/cru/godtools/shared/renderer/content/RenderTabs.kt
module/renderer/src/commonTest/kotlin/org/cru/godtools/shared/renderer/content/RenderTabsTest.kt
module/renderer/src/test/snapshots/images/org.cru.godtools.shared.renderer.content_RenderTabsPaparazziTest_RenderTabs()_-_Tabs.png

Starting to add support for tab elements.  Work in progress.

GT-2673 support rendering tabs elements

---

module/renderer/src/commonMain/kotlin/org/cru/godtools/shared/renderer/content/RenderVideo.kt

- Don't auto-play the video
- Disable looping the video
- Disable full screen mode
- Disable auto-playing the next video

GT-2662 Youtube video config changes
